name: Deploy Demo LMS Candy CBT

on:
  push:
    branches:
      - main

jobs:


  deploy-proxmox-lxc-enterprise:
    runs-on: [self-hosted, LXC, ENTERPRISE]

    strategy:
      fail-fast: false

    steps:

      - name: Prepare Git
        run: |
          ssh root@2.0.2.102 << 'EOF'
            git config --global --add safe.directory /opt/docker/demo_yuukiofuyu_candycbt-redis/app
          EOF

      - name: Update Source Code
        run: |
          ssh root@2.0.2.102 << 'EOF'
            cd /opt/docker/demo_yuukiofuyu_candycbt-redis/app
            git fetch origin
            git reset --hard origin/main
            git clean -fd -e .env
          EOF

      - name: Fix Permission
        run: |
          ssh root@2.0.2.102 << 'EOF'
            chown -R www-data:www-data /opt/docker/demo_yuukiofuyu_candycbt-redis/app
          EOF

      - name: Create .env file
        run: |
          ssh root@2.0.2.102 "printf '%s\n' '${{ secrets.ENV }}' > /opt/docker/demo_yuukiofuyu_candycbt-redis/app/.env"